format ELF executable 3
entry main
segment readable writeable
	w dd 10 dup(0)
segment readable executable
main:
	PUSH EBP
	MOV EBP, ESP
	SUB ESP, 4
	SUB ESP, 40
	MOV EAX, 2
	NEG EAX
	PUSH EAX
	MOV EAX, 0
	MOV EBX,4			; line 6
	MUL EBX
	MOV EBX, EAX
	POP EAX
	MOV [w+EBX], EAX			; line 6
	MOV EAX, 0
	MOV EBX,4			; line 7
	MUL EBX
	MOV EBX, EAX
	MOV EAX,[w+EBX]			; line 7
	PUSH EAX
	MOV EAX, 0
	MOV EBX,4			; line 7
	MUL EBX
	NEG EAX
	ADD EAX, -8
	MOV ESI, EAX
	POP EAX
	MOV [EBP+ESI], EAX			; line 7
	MOV EAX, 0
	MOV EBX,4			; line 8
	MUL EBX
	NEG EAX
	ADD EAX, -8
	MOV ESI, EAX
	MOV EAX,[EBP+ESI]			; line 8
	MOV [EBP-4], EAX			; line 8
	MOV EAX, [EBP-4]		; print i
	CALL OUTDEC			; line 9
	MOV EAX, 0
	MOV EBX,4			; line 10
	MUL EBX
	MOV EBX, EAX
	MOV EAX, [w+EBX]			; line 10

	PUSH EAX
	INC EAX
	MOV [w+EBX], EAX
	MOV EAX, 1
	MOV EBX,4			; line 10
	MUL EBX
	NEG EAX
	ADD EAX, -8
	MOV ESI, EAX
	POP EAX
	MOV [EBP+ESI], EAX			; line 10
	MOV EAX, 1
	MOV EBX,4			; line 11
	MUL EBX
	NEG EAX
	ADD EAX, -8
	MOV ESI, EAX
	MOV EAX,[EBP+ESI]			; line 11
	MOV [EBP-4], EAX			; line 11
	MOV EAX, [EBP-4]		; print i
	CALL OUTDEC			; line 12
	MOV EAX, 0
	MOV EBX,4			; line 13
	MUL EBX
	MOV EBX, EAX
	MOV EAX,[w+EBX]			; line 13
	MOV [EBP-4], EAX			; line 13
	MOV EAX, [EBP-4]		; print i
	CALL OUTDEC			; line 14
	MOV EAX, 0
	PUSH EAX
	MOV EAX,[EBP-4]			; line 16
	POP EBX
	ADD EAX, EBX
	MOV [EBP-4], EAX			; line 16
	MOV EAX, 0
	PUSH EAX
	MOV EAX,[EBP-4]			; line 17
	POP EBX
	SUB EAX, EBX
	MOV [EBP-4], EAX			; line 17
	MOV EAX, 1
	PUSH EAX
	MOV EAX,[EBP-4]			; line 18
	POP EBX
	MUL EBX
	MOV [EBP-4], EAX			; line 18
	MOV EAX, [EBP-4]		; print i
	CALL OUTDEC			; line 19
	MOV EAX, 0
	PUSH EAX
	MOV EAX,[EBP-4]			; line 21
	POP EBX
	CMP EAX, EBX
	JG L0
	MOV EAX, 0
	JMP L1
L0:
	MOV EAX, 1
L1:
	TEST EAX, EAX
	JE L2
	MOV EAX, 10
	PUSH EAX
	MOV EAX,[EBP-4]			; line 21
	POP EBX
	CMP EAX, EBX
	JL L3
	MOV EAX, 0
	JMP L4
L3:
	MOV EAX, 1
L4:
	TEST EAX, EAX 			; line 21
	JE L2
	MOV EAX, 1
	JMP L5
L2:
	MOV EAX, 0
L5:
	TEST EAX, EAX
	JNE L6
	MOV EAX, 0
	PUSH EAX
	MOV EAX,[EBP-4]			; line 21
	POP EBX
	CMP EAX, EBX
	JL L7
	MOV EAX, 0
	JMP L8
L7:
	MOV EAX, 1
L8:
	TEST EAX, EAX
	JE L9
	MOV EAX, 10
	NEG EAX
	PUSH EAX
	MOV EAX,[EBP-4]			; line 21
	POP EBX
	CMP EAX, EBX
	JG L10
	MOV EAX, 0
	JMP L11
L10:
	MOV EAX, 1
L11:
	TEST EAX, EAX 			; line 21
	JE L9
	MOV EAX, 1
	JMP L12
L9:
	MOV EAX, 0
L12:
	TEST EAX, EAX 			; line 21
	JNE L6
	MOV EAX, 0
	JMP L13
L6:
	MOV EAX, 1
L13:
	TEST EAX, EAX			; line 21
	JE L14
	MOV EAX, 100
	MOV [EBP-4], EAX			; line 22
	JMP L15
L14:
	MOV EAX, 200
	MOV [EBP-4], EAX			; line 24
L15:
	MOV EAX, [EBP-4]		; print i
	CALL OUTDEC			; line 25
	MOV EAX, 0
	JMP main_exit			; line 27
main_exit:

	MOV EAX, 1    ; syscall number: sys_exit
	XOR EBX, EBX  ; exit code 0 (success)
	INT 0x80



; ---- OUTDEC: print integer in EAX as decimal, followed by newline ----
OUTDEC:
	PUSH EBX
	PUSH ECX
	PUSH EDX
	PUSH ESI
	OR   EAX, EAX
	JGE  OUTDEC_POSITIVE
	NEG  EAX
	PUSH EAX
	SUB  ESP, 4
	MOV  byte [ESP], '-'
	MOV  EAX, 4
	MOV  EBX, 1
	MOV  ECX, ESP
	MOV  EDX, 1
	INT  0x80
	ADD  ESP, 4
	POP  EAX
OUTDEC_POSITIVE:
	XOR  ECX, ECX
	MOV  EBX, 10
OUTDEC_DIGIT_LOOP:
	XOR  EDX, EDX
	DIV  EBX
	ADD  DL, 30h
	PUSH EDX
	INC  ECX
	TEST EAX, EAX
	JNZ  OUTDEC_DIGIT_LOOP
	MOV  ESI, ECX
	MOV  EBX, 1
	MOV  EDX, 1
OUTDEC_PRINT_LOOP:
	TEST ESI, ESI
	JZ   OUTDEC_NEWLINE
	MOV  EAX, 4
	MOV  ECX, ESP
	INT  0x80
	ADD  ESP, 4
	DEC  ESI
	JMP  OUTDEC_PRINT_LOOP
OUTDEC_NEWLINE:
	SUB  ESP, 4
	MOV  byte [ESP], 10
	MOV  EAX, 4
	MOV  ECX, ESP
	INT  0x80
	ADD  ESP, 4
	POP  ESI
	POP  EDX
	POP  ECX
	POP  EBX
	RET
